### ISSUE TITLE
Priority to middle chunks

### ISSUE THREAD

**Issue by joeveiga** [addaleax/even-chunks#1]
Hi, I'm wondering if there is a way to give priority to the middle chunks. For example:

`evenChunks([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 4); // [[1, 2], [3, 4, 5], [6, 7, 8], [9, 10]]`

Thanks!

**Comment by addaleax** [comment]
```console
$ npm publish
+ even-chunks@1.1.0
```

Let me know if that works for you!

**Comment by joeveiga** [comment]
Awesome! Works like a charm :+1:
